### ISSUE TITLE
Pod library?

### ISSUE THREAD

**Issue by paoloandrea** [pjebs/EasySocial#1]
Can you add to cocoapods EasySocial?

**Comment by pjebs** [comment]
I definitely want to create a pod library.

I had a quick look at the cocoapods website and it looked very confusing. I will need some spare time in the near future to properly read the information and do the bare minimum steps and create the bare minimum files to create it and put it in the cocoapods repository.

If anyone has done it before (and only if they have done it before), feel free to write down the steps below. I'll have it done within a month otherwise.

**Comment by pjebs** [comment]
pod 'EasySocial', '~> 3'
